import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/header';
import SiteHeader from '@/components/site-header';
import { TailwindIndicator } from '@/components/tailwind-indicator';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}, container flex flex-col items-center min-h-screen px-4 lg:px-80`}
      >
        <section className="container relative">
          <Header />
          <SiteHeader />
        </section>
        {children}
        <TailwindIndicator />
      </body>
    </html>
  );
}
